src/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::put('/category/search', 'CategoryController@search')->name('category.search');
Route::put('/product/search', 'ProductController@search')->name('product.search');
Route::resource('product', 'ProductController');
Route::resource('category', 'CategoryController');

src/app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use SoftDeletes;

    protected $fillable = ['name', 'description'];

    protected $dates = ['deleted_at'];

    public function categories() {
        return $this->belongsToMany('App\Models\Category', 'product_categories');
    }

    public function images() {
        return $this->hasMany('App\Models\ProductImage');
    }
}

src/app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use App\Models\Category;
use App\Models\ProductImage;
use Illuminate\Http\Request;
use DB;
use Validator;

class ProductController extends Controller
{
    private $path = 'images/product';

    public function __construct() 
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::get();
        $categories = Category::get();
        $selectedCat = [];

        return view('product.index', compact('products', 'categories', 'selectedCat'));
    }

    /**
     * Search for a product.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::get();

        return view('product.add', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request)
    {
        $name = $request->input('name');
        $selectedCat = $request->input('category');

        $query = DB::table('products')
                    ->select('products.id', 'products.name', 'products.description')
                    ->join('product_categories', 'products.id', '=', 'product_categories.product_id')
                    ->join('categories', 'product_categories.category_id', '=', 'categories.id')
                    ->groupBy('products.id', 'products.name', 'products.description');

        if (!empty($name) && !empty($selectedCat)) {
            $query->where('products.name', 'like', '%' . $name . '%');
            $query->whereIn('categories.id', $selectedCat);
        } else if (!empty($name)) {
            $query->where('products.name', 'like', '%' . $name . '%');
        } else if (!empty($selectedCat)) {
            $query->whereIn('categories.id', $selectedCat);
        }

        $categories = Category::get();
        $products = $query->get();

        if (empty($selectedCat)) {
            $selectedCat = [];
        }

        return view('product.index', compact('products', 'categories', 'selectedCat'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|min:10|max:255',
            'description' => 'required',
        ]);

        if (!$validator->fails()) {
            $images = $request->file('images');

            $product = Product::create([
                'name' => $request->input('name'),
                'description' => $request->input('description'),
            ]);

            if (!empty($product) && !empty($images)) {
                foreach ($images as $key => $row) {
                    if (!empty($row)) {
                        $fileName = time() . $key . '.' . $row->getClientOriginalExtension();
                        $row->move($this->path, $fileName);
                        $image = new ProductImage;
                        $image->product_id = $product->id;
                        $image->image = $fileName;
                        $image->save();
                    }
                }
            }

            $product->categories()->sync($request->input('category'));
        }

        return redirect()->route('product.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        $product = Product::find($product->id);

        if (!empty($product)) {
            $categories = Category::get();
            $images = ProductImage::where('product_id', $product->id)->get();
            $selectedCat = [];

            foreach ($product->categories as $category) {
                $selectedCat[] = $category->pivot->category_id;
            }

            return view(
                'product.edit', 
                compact('product', 'categories', 'selectedCat', 'images')
            );
        }

        return redirect()->route('product.index');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $images = $request->file('images');
        $category = $request->input('category');

        $product = Product::find($product->id);

        if (!empty($product)) {
            if (!empty($images)) {
                foreach($images as $key => $row) {
                    if (!empty($row)) {
                        $fileName = time() . $key . '.' . $row->getClientOriginalExtension();
                        $row->move($this->path, $fileName);
                        $image = new ProductImage;
                        $image->product_id = $product->id;
                        $image->image = $fileName;
                        $image->save();
                    }
                }
            }

            if (!empty($category)) {
                $product->categories()->sync($category);
            }

            $product->update([
                'name' => $request->input('name'),
                'description' => $request->input('description'),
            ]);

            return redirect()->route('product.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product = Product::find($product->id);

        if (!empty($product)) {
            $images = ProductImage::where('product_id', $product->id)->get();
            
            if (!empty($images)) {
                foreach ($images as $row) {
                    if(file_exists($this->path . '/' . $row->image)) {
                        unlink($this->path . '/' . $row->image);
                    }
                }
            }

            $product->categories()->detach();
            $product->images()->delete();
            $result = $product->delete();
        }

        return redirect()->route('product.index');
    }
}

src/resources/views/product/add.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
            	<ol class="breadcrumb panel-heading">
                	<li><a href="{{route('product.index')}}">Produtos</a></li>
                	<li class="active">Adicionar</li>
                </ol>
                <div class="panel-body">
	                <form action="{{ route('product.store') }}" method="POST" enctype="multipart/form-data">
	                	{{ csrf_field() }}
						<div class="form-group">
						  	<label for="name">Nome</label>
						    <input type="text" class="form-control" name="name" id="name" placeholder="Nome">
						</div>
                        <div class="form-group">
                            <label for="name">Categorias</label>
                            <select name="category[]" class="form-control selectpicker" multiple="" data-live-search="true" title="Categorias">
                                @foreach($categories as $category)
                                <option value="{{ $category->id }}">{{ $category->name }}</option>
                                @endforeach()
                            </select>
                            <p class="help-block">Use Crtl para selecionar.</p>
                        </div>
                        <div class="control-group input-images">
                            <button type="button" class="btn btn-info" id="moreimages">Mais...</button>
                            <br />
                            <br />
                            <div class="controls">
                                <input name="images[]" type="file">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="description">Descrição</label>
                            <textarea class="form-control" rows="3" name="description" id="description"></textarea>
                        </div>
						<br />
						<button type="submit" class="btn btn-primary">Salvar</button>
	                </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

src/resources/views/product/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
            	<ol class="breadcrumb panel-heading">
                	<li><a href="{{route('product.index')}}">Produtos</a></li>
                	<li class="active">Editar</li>
                </ol>
                <div class="panel-body">
	                <form action="{{ route('product.update', $product->id) }}" method="POST" enctype="multipart/form-data">
                        {{ method_field('PUT') }}
	                	{{ csrf_field() }}
						<div class="form-group">
						  	<label for="name">Nome</label>
						    <input type="text" class="form-control" name="name" id="name" placeholder="Nome" value="{{ $product->name }}">
						</div>
                        <div class="form-group">
                            <label for="name">Categorias</label>
                            <select name="category[]" class="form-control selectpicker" multiple="" data-live-search="true" title="Categorias">
                                <?php foreach($categories as $category){ ?>
                                    <option value="<?= $category->id ?>" <?= in_array($category->id, $selectedCat) ? "selected" : NULL ; ?>><?= $category->name ?></option>
                                <?php } ?>
                            </select>
                            <p class="help-block">Use Crtl para selecionar.</p>
                        </div>
                        <div class="form-group">
                            <label for="name">Imagens</label>
                            @foreach($images as $image)
                            <img src="/images/product/{{ $image->image }}"  width="10%" />
                            @endforeach
                        </div>
                        <div class="control-group">
                            <button type="button" class="btn btn-info btn-xs" id="moreimages"><i class="glyphicon glyphicon-plus"></i></button>
                            <br>
                            <div class="controls input-images">
                                <input name="images[]" type="file">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="description">Descrição</label>
                            <textarea class="form-control" rows="3" name="description" id="description">{{ $product->description }}</textarea>
                        </div>
						<br />
						<button type="submit" class="btn btn-primary">Salvar</button>
	                </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

src/resources/views/product/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <ol class="breadcrumb panel-heading">
                    <li class="active">Produtos</li>
                </ol>
                <div class="panel-body">
                    <form class="form-inline" action="{{ route('product.search') }}" method="POST">
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}
                        <div class="form-group" style="float: right;">
                            <p><a href="{{route('product.create')}}" class="btn btn-info btn-sm"><i class="glyphicon glyphicon-plus"></i> Adicionar</a></p>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" id="name" name="name" placeholder="Produto">
                        </div>
                        <div class="form-group" style="width: 200px; max-width: 200px;">
                            <select name="category[]" class="form-control selectpicker" multiple="" data-live-search="true" title="Categorias">
                                <?php 
                                if(!empty($categories)){
                                    foreach($categories as $category){ ?>
                                    <option value="<?= $category->id ?>" <?= in_array($category->id, $selectedCat) ? "selected" : NULL ; ?>><?= $category->name ?></option>
                                <?php }
                            } ?>
                            </select>
                        </div>
                        <button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-search"></i> Buscar</button>
                    </form>
                    <br>
                    <table class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Cod</th>
                                <th>Nome</th>
                                <th>Descrição</th>
                                <th>Ação</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($products as $product)
                                <tr>
                                    <th scope="row" class="text-center">{{ $product->id }}</th>
                                    <td>{{ $product->name }}</td>
                                    <td class="text-justify">{{ $product->description }}</td>
                                    <td width="155" class="text-center">
                                        <a href="{{route('product.edit', $product->id)}}" class="btn btn-default btn-sm"><i class="glyphicon glyphicon-pencil"></i></a>
                                        <form action="{{ route('product.destroy', $product) }}" method="POST" style="display: inline-block">
                                            {{ method_field('DELETE') }}
                                            {{ csrf_field() }}
                                            <button type="submit" class="btn btn-danger btn-sm"><i class="glyphicon glyphicon-trash"></i></button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection